In [2]:
# Ques 1
# 1st question
import numpy as np
arr= np.random.randint(0,1,(2,2))
print(arr)

[[0 0]
 [0 0]]


In [3]:
# 2nd question
import numpy as np
import random
arr= np.random.randint(1,2,(4,2))
print(arr)


[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [4]:
# 3rd 4th and 5th question
import numpy as np
filled_array = np.full((3, 3),fill_value= 7)
print(filled_array)
ones_like = np.ones_like(filled_array)
print(ones_like)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
# 6th ques
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]
