In [1]:
# Ques 1
import numpy as np
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [2]:
# Ques 2
import numpy as np
array_0_8= np.reshape((np.arange(0,9)),(3,3))
print(array_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# Ques 3
import numpy as np
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Ques 4
import numpy as np
random_array = np.random.rand(30)
mean_arr = random_array.mean()
print(mean_arr)

0.4026398732370809


In [5]:
# Ques 5 
import numpy as np 
array = np.random.randint(1,100,size=(10,10))
min_val = array.min()
max_val = array.max()
print("The random elements array is: ",array)
print("The min value of the matrix is:",min_val)
print("The max value of the matrix is:",max_val)

The random elements array is:  [[87 12 70 82 34 39 65 87 93 10]
 [11 36 28 94 44 60 51  1 66  6]
 [91 78 99 54 50 29 79 29 62 34]
 [15 68 29 70 94 66 30 83 22 59]
 [76  2  1 79 48 53 31 88 68 38]
 [75 82 66 28 38 89 81 31  8 42]
 [45 52 44 96 80 71  3 90 34  3]
 [19 55 76 13 40 22 50 20 89 39]
 [ 3 98 21 39  5 40 73 29 79 50]
 [92 87 97 14 74 62 36 89 55 83]]
The min value of the matrix is: 1
The max value of the matrix is: 99


In [6]:
# Ques 6
import numpy as np
array = np.zeros((10,10))
print(array)
array[0][4]= 1
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:

# Ques 7
import numpy as np
array = [1,2,0,0,4,0]
array.reverse()
# array.sort()
print(array)


[0, 4, 0, 0, 2, 1]


In [8]:
# Ques 8
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0,:]=1
array[-1,:] =1
array[:,0]=1
array[:,-1]=1
print(array)


[[1 1 1]
 [1 5 1]
 [1 1 1]]


In [9]:
# Ques 9 
import numpy as np
check = np.random.randint(0,1,(8,8))
check[1::2, ::2] = 1 
check[::2, 1::2] = 1 
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
