In [1]:
# Ques 1
import numpy as np
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])
result1 = x+y
result2 = np.add(x,y)
print(result1)
print(result2)

v = np.array([9,10]) 
w = np.array([11,12])
result1 = np.add(v,w)
print(result1)

[[ 6  8]
 [10 13]]
[[ 6  8]
 [10 13]]
[20 22]


In [1]:
# Ques 2
import numpy as np
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])
result = np.subtract(x,y)
print(result)

v = np.array([9,10]) 
w = np.array([11,12])
result = np.subtract(v,w)
print(result)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [3]:
# Ques 3
import numpy as np
v = np.array([9,10]) 
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])

res1 = v*2
res2= w*3
res3 = x*4
res4=y*5

print(res1)
print(res2)
print(res3)
print(res4)

[18 20]
[33 36]
[[ 4  8]
 [12 20]]
[[25 30]
 [35 40]]


In [2]:
# Ques 4
import numpy as np
v = np.array([9,10]) 
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])

square1 = np.square(v)
square2 = np.square(w)
square3 = np.square(x)
square4 = np.square(y)
print(square1,"\n", square2,"\n", square3,"\n", square4)

[ 81 100] 
 [121 144] 
 [[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]]


In [5]:
# Ques 5
import numpy as np
v = np.array([9,10]) 
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])

result1 = np.dot(v,w)
result2 = np.dot(x,v)
result3 =np.dot(x,y)

print(result1)
print(result2)
print(result3)

219
[29 77]
[[19 22]
 [50 58]]


In [6]:
# Ques 6
import numpy as np
v = np.array([9,10]) 
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])
result1 = np.concatenate((v,w))
result2 = np.concatenate((x,y),axis = 1)
print(result1)
print(result2)
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

[ 9 10 11 12]
[[1 2 5 6]
 [3 5 7 8]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Ques 7
import numpy as np
v = np.array([9,10]) 
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]]) 
y = np.array([[5,6]
            , [7,8]])
result3 = np.concatenate((x,v))
print(result3)
# dimensional error